Level 1

Loading & inspection

1. Import Pandas.

In [1]:
import pandas as pd

2. Read students.csv.

In [2]:
students = pd.read_csv("/Users/prathmeshsurwase/Desktop/Pandas /DataFrameP/CommenData/students.csv")
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

3. Display the first 5 rows.

In [3]:
students.head()

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000

4. Display the last 5 rows.

In [4]:
students.tail()

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

5. Find the number of rows and columns.

In [5]:
students.shape

(510, 9)

6. Display column names.

In [8]:
print(students.columns)

Index(['student_id', 'name', 'age', 'gender', 'city', 'course', 'marks',
       'attendance', 'fees_paid'],
      dtype='str')

7. Display data types.

In [9]:
students.dtypes

student_id      int64
name              str
age             int64
gender            str
city              str
course            str
marks         float64
attendance    float64
fees_paid       int64
dtype: object

8. Generate statistical summary.

In [11]:
students.describe()

        student_id         age       marks  attendance     fees_paid
count   510.000000  510.000000  504.000000  503.000000    510.000000
mean   1250.239216   21.343137   72.005952   83.544930  53941.176471
std     144.358977    2.299291   14.130813    9.131789   8546.444854
min    1001.000000   18.000000   25.000000   55.100000  45000.000000
25%    1126.250000   19.000000   62.000000   77.450000  45000.000000
50%    1250.000000   21.000000   73.000000   84.200000  50000.000000
75%    1374.750000   23.000000   82.000000   90.050000  60000.000000
max    1500.000000   25.000000  100.000000  100.000000  70000.000000

9. Check how many missing values exist in each column.

In [14]:
print((students.isnull()).sum())

student_id    0
name          0
age           0
gender        0
city          8
course        5
marks         6
attendance    7
fees_paid     0
dtype: int64

10. Check whether student_id contains duplicate values.

In [16]:
students[students['student_id'].duplicated()]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
500,1309,Student_309,19,M,Mumbai,Java,84.0,75.6,45000
501,1014,Student_014,18,M,Bangalore,Machine Learning,66.0,69.9,65000
502,1415,Student_415,22,F,Hyderabad,Java,69.0,84.3,45000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000