🟡 LEVEL 5 — Creating & Updating Columns

In [1]:
import pandas as pd 
import numpy as np

In [2]:
students = pd.read_csv("/Users/prathmeshsurwase/Desktop/Pandas /DataFrameP/CommenData/students.csv")
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

41. Create a column:
result = Pass / Fail

Condition:
marks >= 40 → Pass
marks < 40 → Fail

In [3]:
students['result'] = students['marks'].apply(lambda x :  'Pass' if x >= 40 else 'Fail' )

In [4]:
students['result'] = np.where(students['marks'] > 40 , 'Pass' , 'fail')

In [5]:
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,result
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000,Pass
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000,Pass
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000,Pass
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000,Pass
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000,Pass
...,...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000,Pass
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000,Pass
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000,Pass
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000,Pass
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000,Pass

42. Create:
percentage = marks

Assume marks are already out of 100.

In [6]:
students['marks'] = (students['marks']/100)*100

In [7]:
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,result
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000,Pass
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000,Pass
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000,Pass
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000,Pass
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000,Pass
...,...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000,Pass
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000,Pass
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000,Pass
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000,Pass
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000,Pass

43. Create:
attendance_status

- = 90 → Excellent
- = 75 → Good
- < 75 → Poor

In [8]:
students["attendance_status"] = students['attendance'].apply(lambda x : 'Excellent' if x > 90 else 'Good' if x == 75 else 'Poor')

In [9]:
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,result,attendance_status
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000,Pass,Poor
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000,Pass,Excellent
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000,Pass,Poor
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000,Pass,Poor
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000,Pass,Poor
...,...,...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000,Pass,Poor
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000,Pass,Excellent
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000,Pass,Poor
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000,Pass,Excellent
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000,Pass,Poor

44. Create:
performance

- 90+ → Excellent
- 80–89 → Very Good
- 70–79 → Good
- 60–69 → Average
- <60 → Poor

In [10]:
students['perfromance'] = students['marks'].apply(lambda x : 'Excellent' if x > 90 else 'Very Good' if x < 90 or x >80 else 'good' if x < 79 or x >70 else 'Average'  if x < 69 or x > 60  else 'poor')

45. Create a passed Boolean column.

In [11]:
students['Boolean'] = students['marks'] > 40

In [12]:
students['Boolean']

0      True
1      True
2      True
3      True
4      True
       ...
505    True
506    True
507    True
508    True
509    True
Name: Boolean, Length: 510, dtype: bool

46. Increase every student's marks by 5.

In [13]:
students['marks'] = students['marks'] + 5

In [14]:
students['marks']

0      86.0
1      54.0
2      77.0
3      67.0
4      52.0
       ...
505    55.0
506    65.0
507    92.0
508    67.0
509    89.0
Name: marks, Length: 510, dtype: float64

47. Add a bonus_marks column.

In [15]:
students['Bonus_marks'] = 5

In [16]:
students[['marks' , 'Bonus_marks']]

     marks  Bonus_marks
0     86.0            5
1     54.0            5
2     77.0            5
3     67.0            5
4     52.0            5
..     ...          ...
505   55.0            5
506   65.0            5
507   92.0            5
508   67.0            5
509   89.0            5

[510 rows x 2 columns]

48. Calculate final marks.

In [17]:
(students['marks']) + (students['Bonus_marks'])

0      91.0
1      59.0
2      82.0
3      72.0
4      57.0
       ...
505    60.0
506    70.0
507    97.0
508    72.0
509    94.0
Length: 510, dtype: float64

49. Delete the bonus_marks column.

In [18]:
students.drop(columns=['Bonus_marks'],inplace=True)

In [19]:
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,result,attendance_status,perfromance,Boolean
0,1001,Student_001,19,F,NaN,Python,86.0,81.4,45000,Pass,Poor,Very Good,True
1,1002,Student_002,20,F,Bangalore,Machine Learning,54.0,100.0,65000,Pass,Excellent,Very Good,True
2,1003,Student_003,24,F,Nashik,Java,77.0,85.0,45000,Pass,Poor,Very Good,True
3,1004,Student_004,25,F,Bangalore,Java,67.0,77.2,45000,Pass,Poor,Very Good,True
4,1005,Student_005,21,F,Bangalore,Machine Learning,52.0,74.1,65000,Pass,Poor,Very Good,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,55.0,79.0,60000,Pass,Poor,Very Good,True
506,1250,Student_250,18,F,Delhi,Data Science,65.0,93.6,60000,Pass,Excellent,Very Good,True
507,1218,Student_218,18,M,Mumbai,Python,92.0,79.8,45000,Pass,Poor,Very Good,True
508,1222,Student_222,22,M,Bangalore,Python,67.0,98.5,45000,Pass,Excellent,Very Good,True
509,1294,Student_294,20,M,Nashik,Data Science,89.0,80.2,60000,Pass,Poor,Very Good,True

In [20]:
students.drop(columns="Boolean" , inplace=True)
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid,result,attendance_status,perfromance
0,1001,Student_001,19,F,NaN,Python,86.0,81.4,45000,Pass,Poor,Very Good
1,1002,Student_002,20,F,Bangalore,Machine Learning,54.0,100.0,65000,Pass,Excellent,Very Good
2,1003,Student_003,24,F,Nashik,Java,77.0,85.0,45000,Pass,Poor,Very Good
3,1004,Student_004,25,F,Bangalore,Java,67.0,77.2,45000,Pass,Poor,Very Good
4,1005,Student_005,21,F,Bangalore,Machine Learning,52.0,74.1,65000,Pass,Poor,Very Good
...,...,...,...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,55.0,79.0,60000,Pass,Poor,Very Good
506,1250,Student_250,18,F,Delhi,Data Science,65.0,93.6,60000,Pass,Excellent,Very Good
507,1218,Student_218,18,M,Mumbai,Python,92.0,79.8,45000,Pass,Poor,Very Good
508,1222,Student_222,22,M,Bangalore,Python,67.0,98.5,45000,Pass,Excellent,Very Good
509,1294,Student_294,20,M,Nashik,Data Science,89.0,80.2,60000,Pass,Poor,Very Good

50. Rename fees_paid to fees.

In [21]:
students['fees_paid'].rename('Fees' , inplace=True)

0      45000
1      65000
2      45000
3      45000
4      65000
       ...
505    60000
506    60000
507    45000
508    45000
509    60000
Name: Fees, Length: 510, dtype: int64