🟡 LEVEL 4 — Sorting

In [1]:
import pandas as pd

In [2]:
students = pd.read_csv("/Users/prathmeshsurwase/Desktop/Pandas /DataFrameP/CommenData/students.csv")
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

31. Sort students by marks ascending.

In [3]:
students.sort_values('marks')

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
114,1115,Student_115,18,M,Mumbai,Machine Learning,25.0,61.0,70000
59,1060,Student_060,19,M,Delhi,Machine Learning,35.0,84.6,65000
302,1303,Student_303,25,M,Nashik,Java,38.0,87.5,45000
398,1399,Student_399,24,F,Pune,Python,38.0,87.0,45000
344,1345,Student_345,22,M,Delhi,Machine Learning,40.0,83.2,70000
...,...,...,...,...,...,...,...,...,...
120,1121,Student_121,23,M,Mumbai,Data Science,NaN,95.4,60000
204,1205,Student_205,18,M,Pune,MERN,NaN,65.0,50000
247,1248,Student_248,25,M,Bangalore,Java,NaN,100.0,45000
349,1350,Student_350,23,F,Pune,Machine Learning,NaN,100.0,65000
382,1383,Student_383,25,F,Hyderabad,Machine Learning,NaN,87.6,65000

32. Sort students by marks descending.

In [4]:
students.sort_values('marks',ascending=False)

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
96,1097,Student_097,21,F,Delhi,Data Science,100.0,92.8,60000
495,1496,Student_496,18,F,Delhi,Java,100.0,75.4,45000
345,1346,Student_346,21,F,Bangalore,Java,100.0,75.7,45000
232,1233,Student_233,22,F,Nashik,Data Science,100.0,89.9,60000
432,1433,Student_433,20,F,Pune,MERN,100.0,89.5,50000
...,...,...,...,...,...,...,...,...,...
120,1121,Student_121,23,M,Mumbai,Data Science,NaN,95.4,60000
204,1205,Student_205,18,M,Pune,MERN,NaN,65.0,50000
247,1248,Student_248,25,M,Bangalore,Java,NaN,100.0,45000
349,1350,Student_350,23,F,Pune,Machine Learning,NaN,100.0,65000
382,1383,Student_383,25,F,Hyderabad,Machine Learning,NaN,87.6,65000

33. Find the top 5 students.

In [5]:
students.sort_values('marks' , ascending=False).head()

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
96,1097,Student_097,21,F,Delhi,Data Science,100.0,92.8,60000
495,1496,Student_496,18,F,Delhi,Java,100.0,75.4,45000
345,1346,Student_346,21,F,Bangalore,Java,100.0,75.7,45000
232,1233,Student_233,22,F,Nashik,Data Science,100.0,89.9,60000
432,1433,Student_433,20,F,Pune,MERN,100.0,89.5,50000

34. Find the bottom 3 students.

In [6]:
students.tail(3)

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

35. Sort by course and then by marks.

In [7]:
students.sort_values(['course' , 'marks'] , ascending=[True , False])

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
10,1011,Student_011,21,F,Delhi,Data Science,100.0,97.1,65000
96,1097,Student_097,21,F,Delhi,Data Science,100.0,92.8,60000
232,1233,Student_233,22,F,Nashik,Data Science,100.0,89.9,60000
250,1251,Student_251,22,M,Delhi,Data Science,99.0,77.8,65000
456,1457,Student_457,24,M,Bangalore,Data Science,99.0,64.6,60000
...,...,...,...,...,...,...,...,...,...
79,1080,Student_080,20,M,Mumbai,NaN,96.0,76.9,45000
171,1172,Student_172,22,M,Delhi,NaN,88.0,71.2,70000
60,1061,Student_061,24,F,Delhi,NaN,86.0,80.3,60000
271,1272,Student_272,22,M,Delhi,NaN,83.0,86.6,50000
462,1463,Student_463,24,F,Bangalore,NaN,80.0,71.9,45000

36. Sort by attendance descending.

In [8]:
students.sort_values('attendance' , ascending=False)

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
247,1248,Student_248,25,M,Bangalore,Java,NaN,100.0,45000
268,1269,Student_269,24,F,Hyderabad,Java,100.0,100.0,45000
339,1340,Student_340,25,F,Hyderabad,Data Science,72.0,100.0,65000
87,1088,Student_088,21,M,Hyderabad,Python,69.0,100.0,50000
343,1344,Student_344,22,F,Bangalore,Java,88.0,100.0,45000
...,...,...,...,...,...,...,...,...,...
205,1206,Student_206,20,F,Mumbai,MERN,79.0,NaN,50000
223,1224,Student_224,22,F,Pune,Machine Learning,65.0,NaN,70000
311,1312,Student_312,25,M,Bangalore,Python,61.0,NaN,45000
372,1373,Student_373,23,F,Pune,Java,77.0,NaN,45000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000

37. Find the student with maximum marks.

In [9]:
students.sort_values('marks', ascending=False).head(1)

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
96,1097,Student_097,21,F,Delhi,Data Science,100.0,92.8,60000

38. Find the student with minimum marks.

In [10]:
students.sort_values('marks').head(1)

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
114,1115,Student_115,18,M,Mumbai,Machine Learning,25.0,61.0,70000

39. Find the second-highest marks.

In [11]:
students['marks'].nlargest(2).iloc[-1]

np.float64(100.0)

In [12]:
students['marks'].sort_values(ascending=False).unique()[1]

np.float64(99.0)

40. Find the top 3 students from Python.

In [13]:
students.loc[:2]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000