🟢 LEVEL 2 — Selecting Data

In [1]:
import pandas as pd

In [2]:
students = pd.read_csv("/Users/prathmeshsurwase/Desktop/Pandas /DataFrameP/CommenData/students.csv")
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

11. Select only the name column.

In [3]:
students['name']

0      Student_001
1      Student_002
2      Student_003
3      Student_004
4      Student_005
          ...
505    Student_156
506    Student_250
507    Student_218
508    Student_222
509    Student_294
Name: name, Length: 510, dtype: str

12. Select name, course, and marks.

In [4]:
students[['name' , 'course' , 'marks']]

            name            course  marks
0    Student_001            Python   81.0
1    Student_002  Machine Learning   49.0
2    Student_003              Java   72.0
3    Student_004              Java   62.0
4    Student_005  Machine Learning   47.0
..           ...               ...    ...
505  Student_156      Data Science   50.0
506  Student_250      Data Science   60.0
507  Student_218            Python   87.0
508  Student_222            Python   62.0
509  Student_294      Data Science   84.0

[510 rows x 3 columns]

13. Select the first 5 rows using iloc.

In [5]:
students.loc[4]

student_id                1005
name               Student_005
age                         21
gender                       F
city                 Bangalore
course        Machine Learning
marks                     47.0
attendance                74.1
fees_paid                65000
Name: 4, dtype: object

14. Select rows 2–7 using iloc.

In [6]:
students.iloc[1:7]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
5,1006,Student_006,23,M,Mumbai,MERN,87.0,90.3,50000
6,1007,Student_007,18,F,Nashik,Java,67.0,74.9,50000

15. Select name and marks using loc.

In [7]:
students.loc[:,['name' , 'marks']]

            name  marks
0    Student_001   81.0
1    Student_002   49.0
2    Student_003   72.0
3    Student_004   62.0
4    Student_005   47.0
..           ...    ...
505  Student_156   50.0
506  Student_250   60.0
507  Student_218   87.0
508  Student_222   62.0
509  Student_294   84.0

[510 rows x 2 columns]

16. Find the student at index 5.

In [8]:
students.iloc[5]

student_id           1006
name          Student_006
age                    23
gender                  M
city               Mumbai
course               MERN
marks                87.0
attendance           90.3
fees_paid           50000
Name: 5, dtype: object

17. Select students from index 3 to 8.

In [9]:
students.loc[3:8]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
5,1006,Student_006,23,M,Mumbai,MERN,87.0,90.3,50000
6,1007,Student_007,18,F,Nashik,Java,67.0,74.9,50000
7,1008,Student_008,18,M,Nashik,MERN,76.0,84.8,55000
8,1009,Student_009,20,M,Nashik,Java,75.0,99.8,45000

18. Set student_id as the DataFrame index.

In [10]:
students.set_index('student_id' , inplace=True)

In [11]:
students

,name,age,gender,city,course,marks,attendance,fees_paid
student_id,,,,,,,,
1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...
1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

19. Reset the index.

In [12]:
students.reset_index(inplace=True)

20. Select all female students.

In [13]:
students[students['gender'] == 'F']

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
497,1498,Student_498,25,F,Mumbai,Data Science,53.0,93.0,65000
499,1500,Student_500,22,F,Delhi,Python,100.0,86.1,50000
502,1415,Student_415,22,F,Hyderabad,Java,69.0,84.3,45000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000