🟢 LEVEL 3 — Filtering

In [1]:
import pandas as pd

In [2]:
students = pd.read_csv("/Users/prathmeshsurwase/Desktop/Pandas /DataFrameP/CommenData/students.csv")
students

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
...,...,...,...,...,...,...,...,...,...
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

21. Find students whose marks are greater than 80.

In [3]:
students[students['marks'] > 80]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
5,1006,Student_006,23,M,Mumbai,MERN,87.0,90.3,50000
10,1011,Student_011,21,F,Delhi,Data Science,100.0,97.1,65000
17,1018,Student_018,20,M,Hyderabad,Python,86.0,96.3,50000
19,1020,Student_020,20,F,Delhi,Data Science,89.0,86.3,60000
...,...,...,...,...,...,...,...,...,...
500,1309,Student_309,19,M,Mumbai,Java,84.0,75.6,45000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

22. Find students whose marks are below 70.

In [4]:
students[students['marks'] < 70]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
3,1004,Student_004,25,F,Bangalore,Java,62.0,77.2,45000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
6,1007,Student_007,18,F,Nashik,Java,67.0,74.9,50000
9,1010,Student_010,19,M,Bangalore,Java,67.0,80.9,45000
...,...,...,...,...,...,...,...,...,...
501,1014,Student_014,18,M,Bangalore,Machine Learning,66.0,69.9,65000
502,1415,Student_415,22,F,Hyderabad,Java,69.0,84.3,45000
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000

23. Find students from Pune.

In [5]:
students[students["city"] =='Pune']

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
21,1022,Student_022,22,F,Pune,MERN,69.0,87.6,50000
27,1028,Student_028,24,F,Pune,Machine Learning,88.0,81.6,65000
28,1029,Student_029,21,F,Pune,Data Science,65.0,84.9,60000
40,1041,Student_041,24,M,Pune,MERN,51.0,79.6,50000
45,1046,Student_046,19,M,Pune,Data Science,74.0,81.6,60000
...,...,...,...,...,...,...,...,...,...
470,1471,Student_471,25,F,Pune,Python,94.0,85.4,45000
473,1474,Student_474,21,M,Pune,Machine Learning,72.0,83.4,65000
484,1485,Student_485,23,F,Pune,Python,55.0,90.6,45000
489,1490,Student_490,25,F,Pune,MERN,73.0,84.9,50000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000

24. Find students enrolled in Python.

In [6]:
students[students['course'] == "Python"]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
12,1013,Student_013,19,F,Hyderabad,Python,49.0,78.7,45000
17,1018,Student_018,20,M,Hyderabad,Python,86.0,96.3,50000
25,1026,Student_026,21,F,Bangalore,Python,81.0,75.1,50000
26,1027,Student_027,24,M,Delhi,Python,91.0,77.0,45000
...,...,...,...,...,...,...,...,...,...
494,1495,Student_495,18,M,Bangalore,Python,79.0,94.5,45000
499,1500,Student_500,22,F,Delhi,Python,100.0,86.1,50000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000

25. Find students from Pune who scored above 80.

In [7]:
students[(students['city'] == 'Pune') & (students['marks'] > 80)]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
27,1028,Student_028,24,F,Pune,Machine Learning,88.0,81.6,65000
53,1054,Student_054,25,M,Pune,Data Science,81.0,86.0,60000
101,1102,Student_102,21,M,Pune,Data Science,81.0,83.8,60000
103,1104,Student_104,21,F,Pune,Machine Learning,88.0,76.0,65000
108,1109,Student_109,19,F,Pune,MERN,85.0,64.4,50000
116,1117,Student_117,20,F,Pune,Java,90.0,75.3,50000
118,1119,Student_119,24,M,Pune,Java,92.0,86.8,45000
129,1130,Student_130,22,M,Pune,MERN,85.0,92.0,50000
177,1178,Student_178,24,F,Pune,Python,87.0,80.7,45000
179,1180,Student_180,25,M,Pune,Java,92.0,82.4,45000
222,1223,Student_223,21,M,Pune,Python,100.0,78.9,45000
259,1260,Student_260,21,F,Pune,MERN,92.0,92.0,50000
266,1267,Student_267,24,M,Pune,Machine Learning,81.0,85.9,70000
276,1277,Student_277,19,M,Pune,Machine Learning,88.0,71.5,65000
278,1279,Student_279,24,F,Pune,MERN,86.0,69.9,55000
285,1286,Student_286,25,M,Pune,Java,99.0,82.1,45000
301,1302,Student_302,24,M,Pune,MERN,88.0,78.3,50000
322,1323,Student_323,24,M,Pune,Python,85.0,82.9,45000
389,1390,Student_390,25,F,Pune,Machine Learning,95.0,85.2,65000
406,1407,Student_407,18,F,Pune,Python,94.0,89.2,45000
424,1425,Student_425,18,M,Pune,Data Science,95.0,81.0,65000
432,1433,Student_433,20,F,Pune,MERN,100.0,89.5,50000
451,1452,Student_452,21,M,Pune,Machine Learning,83.0,89.2,65000
460,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
466,1467,Student_467,20,F,Pune,MERN,90.0,74.3,50000
470,1471,Student_471,25,F,Pune,Python,94.0,85.4,45000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000

26. Find students whose marks are between 70 and 90.

In [8]:
students[students['marks'].between(70,90)]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
0,1001,Student_001,19,F,NaN,Python,81.0,81.4,45000
2,1003,Student_003,24,F,Nashik,Java,72.0,85.0,45000
5,1006,Student_006,23,M,Mumbai,MERN,87.0,90.3,50000
7,1008,Student_008,18,M,Nashik,MERN,76.0,84.8,55000
8,1009,Student_009,20,M,Nashik,Java,75.0,99.8,45000
...,...,...,...,...,...,...,...,...,...
498,1499,Student_499,20,M,Bangalore,Data Science,82.0,93.0,60000
500,1309,Student_309,19,M,Mumbai,Java,84.0,75.6,45000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000
507,1218,Student_218,18,M,Mumbai,Python,87.0,79.8,45000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

27. Find students whose attendance is greater than 90.

In [9]:
students[students['attendance'] > 90]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
5,1006,Student_006,23,M,Mumbai,MERN,87.0,90.3,50000
8,1009,Student_009,20,M,Nashik,Java,75.0,99.8,45000
10,1011,Student_011,21,F,Delhi,Data Science,100.0,97.1,65000
15,1016,Student_016,18,M,Delhi,MERN,80.0,91.8,50000
...,...,...,...,...,...,...,...,...,...
497,1498,Student_498,25,F,Mumbai,Data Science,53.0,93.0,65000
498,1499,Student_499,20,M,Bangalore,Data Science,82.0,93.0,60000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
508,1222,Student_222,22,M,Bangalore,Python,62.0,98.5,45000

28. Find female students from Mumbai.

In [10]:
students[(students['city'] == 'Mumbai') & (students['gender'] == 'F')]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
31,1032,Student_032,18,F,Mumbai,MERN,71.0,68.0,50000
51,1052,Student_052,18,F,Mumbai,Java,76.0,85.7,45000
56,1057,Student_057,19,F,Mumbai,Java,90.0,77.5,45000
68,1069,Student_069,23,F,Mumbai,Java,57.0,86.8,45000
72,1073,Student_073,19,F,Mumbai,Python,56.0,74.3,45000
92,1093,Student_093,22,F,Mumbai,MERN,77.0,78.9,50000
115,1116,Student_116,19,F,Mumbai,Machine Learning,59.0,79.6,65000
160,1161,Student_161,18,F,Mumbai,Machine Learning,67.0,78.2,65000
175,1176,Student_176,25,F,Mumbai,Python,69.0,85.5,45000
205,1206,Student_206,20,F,Mumbai,MERN,79.0,NaN,50000
226,1227,Student_227,21,F,Mumbai,MERN,78.0,69.5,50000
261,1262,Student_262,20,F,Mumbai,Machine Learning,100.0,75.1,70000
269,1270,Student_270,19,F,Mumbai,Java,71.0,73.2,50000
272,1273,Student_273,22,F,Mumbai,Machine Learning,55.0,95.5,70000
277,1278,Student_278,21,F,Mumbai,Machine Learning,70.0,87.5,65000
305,1306,Student_306,24,F,Mumbai,Java,77.0,75.1,50000
337,1338,Student_338,18,F,Mumbai,MERN,79.0,79.5,50000
376,1377,Student_377,20,F,Mumbai,Data Science,47.0,94.4,60000
381,1382,Student_382,25,F,Mumbai,Java,82.0,86.0,50000
386,1387,Student_387,22,F,Mumbai,Data Science,53.0,91.7,65000
394,1395,Student_395,19,F,Mumbai,Python,75.0,81.3,45000
395,1396,Student_396,25,F,Mumbai,Machine Learning,61.0,88.8,65000
401,1402,Student_402,18,F,Mumbai,MERN,89.0,72.4,55000
417,1418,Student_418,18,F,Mumbai,Data Science,58.0,86.2,60000
454,1455,Student_455,20,F,Mumbai,Java,84.0,97.8,45000
464,1465,Student_465,18,F,Mumbai,Machine Learning,67.0,86.7,70000
465,1466,Student_466,18,F,Mumbai,Data Science,79.0,90.5,60000
467,1468,Student_468,19,F,Mumbai,Machine Learning,96.0,85.5,65000
496,1497,Student_497,18,F,Mumbai,MERN,54.0,88.3,55000
497,1498,Student_498,25,F,Mumbai,Data Science,53.0,93.0,65000

29. Find students who paid more than ₹50,000.

In [11]:
students[students['fees_paid'] > 50000]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
7,1008,Student_008,18,M,Nashik,MERN,76.0,84.8,55000
10,1011,Student_011,21,F,Delhi,Data Science,100.0,97.1,65000
13,1014,Student_014,18,M,Bangalore,Machine Learning,66.0,69.9,65000
...,...,...,...,...,...,...,...,...,...
501,1014,Student_014,18,M,Bangalore,Machine Learning,66.0,69.9,65000
503,1033,Student_033,18,F,Delhi,Data Science,84.0,NaN,60000
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000
506,1250,Student_250,18,F,Delhi,Data Science,60.0,93.6,60000
509,1294,Student_294,20,M,Nashik,Data Science,84.0,80.2,60000

30. Find students whose marks are either below 60 or above 90.

In [12]:
students[(students['marks'] < 60) | (students["marks"] > 90)]

,student_id,name,age,gender,city,course,marks,attendance,fees_paid
1,1002,Student_002,20,F,Bangalore,Machine Learning,49.0,100.0,65000
4,1005,Student_005,21,F,Bangalore,Machine Learning,47.0,74.1,65000
10,1011,Student_011,21,F,Delhi,Data Science,100.0,97.1,65000
12,1013,Student_013,19,F,Hyderabad,Python,49.0,78.7,45000
16,1017,Student_017,19,M,Hyderabad,Java,56.0,84.8,50000
...,...,...,...,...,...,...,...,...,...
496,1497,Student_497,18,F,Mumbai,MERN,54.0,88.3,55000
497,1498,Student_498,25,F,Mumbai,Data Science,53.0,93.0,65000
499,1500,Student_500,22,F,Delhi,Python,100.0,86.1,50000
504,1461,Student_461,24,M,Pune,Python,100.0,91.2,45000
505,1156,Student_156,19,M,Bangalore,Data Science,50.0,79.0,60000